site_name: Agrisemantics
theme: 'mkdocs'
repo_url: https://github.com/agrisemantics/website
repo_name: 'Github'
edit_uri: 'edit/master/docs/'
site_description: 'Agrisemantics home page'
nav:
- Home : index.md
- Global Agricultural Concept Space: GACS.md
